---
title: "calculateCV_saliva"
author: "Nandi"
date: "25 September 2018"
output: html_document
---

```{r, include=FALSE}
#LOAD PACKAGES AND SET DIRECTORIES

packages <- c("ggplot2","tidyr","stringr","knitr","corrplot","data.table","readxl","gridExtra","dplyr", "psych","kableExtra","lavaan","xlsx","DescTools")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)

cas_dir <- '/Volumes/psych-cog/dsnlab/TAG/'
saliva_dir <- paste0(cas_dir,'behavior/Puberty/Saliva/Wave1')
options(digits=3)
```

###IMPORT TAG OVERVIEW DOC FROM CAS
```{r, include = F}
#import "overview" document so that we can filter analyses to subjects that were not excluded

overview <- read.xlsx(paste0(cas_dir,'behavior/Overview/Overview_Withdrawn_Completed/TAG_Overview_Doc.xlsx'),1)
overview <- overview[,c("TAG_ID","W1S2_Completed","Withdrawn_W1","Exclusionary_Withdrawl")]

#removing everyone who withdrew at W1 (exclusionary withdrawals & Withdrawn_W1)
overview <- overview %>% 
  rename(SID = TAG_ID) %>%
  replace_na(list(Withdrawn_W1 = 0)) %>%
  replace_na(list(Exclusionary_Withdrawl = 0)) %>% 
  arrange(Exclusionary_Withdrawl) %>% 
  mutate(SID=gsub("[^0-9\\.]", "", SID)) %>%
  filter(Exclusionary_Withdrawl==0) %>%
  filter(Withdrawn_W1==0)
```

###CALCULATE INTRA-ASSAY CVS
```{r}

#batch 1
#import files
Saliva_DHEA_CV_1 <- read_xlsx(paste0(saliva_dir,'/TAG_SALIVA_Master_File.xlsx'), sheet=1)
Saliva_TEST_CV_1 <- read_xlsx(paste0(saliva_dir,'/TAG_SALIVA_Master_File.xlsx'), sheet=5)
Saliva_EST_CV_1 <- read_xlsx(paste0(saliva_dir,'/TAG_SALIVA_Master_File.xlsx'), sheet=9)

#clean and calculate interassay CV for concentrations and optical densities
Saliva_DHEA_CV_1 <- Saliva_DHEA_CV_1 %>%
  rename(WellID = `Well ID`,
         ID = Name,
         Conc = `[Concentration]`,
         OD = `450`) %>%
  filter(!(WellID=="SPL37" & ID=="28.1")) %>%
  filter(!(WellID=="SPL38" & ID=="28.2")) %>%
  mutate(Conc = as.numeric(Conc),
         OD = as.numeric(OD),
         Conc_2 = lead(Conc),
         OD_2 = lead(OD)) %>% 
  select(ID,Conc,Conc_2,OD,OD_2) %>%
  filter(!is.na(ID)) %>%
  rowwise() %>%
  mutate(Conc_mean = mean(c(Conc,Conc_2),na.rm=T),
         Conc_sd = sd(c(Conc,Conc_2),na.rm=T),
         OD_mean = mean(c(OD,OD_2),na.rm=T),
         OD_sd = sd(c(OD,OD_2),na.rm=T)) %>%
  mutate(DHEA_Conc_CV = 100*(Conc_sd/Conc_mean),
         DHEA_Conc_CV = round(as.numeric(DHEA_Conc_CV),3),
         DHEA_OD_CV = 100*(OD_sd/OD_mean),
         DHEA_OD_CV = round(as.numeric(DHEA_OD_CV),3),
         SID = as.factor(round(as.numeric(ID),2))) %>%
  select(SID,DHEA_Conc_CV,DHEA_OD_CV) %>%
  filter(!is.na(SID)) %>%
  filter(!SID == "0.1") %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID)) %>%
  arrange(SID) 

Saliva_TEST_CV_1 <- Saliva_TEST_CV_1 %>% 
  rename(WellID = `Well ID`,
         ID = Name,
         Conc = `[Concentration]`,
         OD = `450`) %>%
  filter(!(WellID=="SPL20" & ID=="44.1")) %>%
  mutate(Conc = as.numeric(Conc),
         OD = as.numeric(OD),
         Conc_2 = lead(Conc),
         OD_2 = lead(OD)) %>% 
  select(ID,Conc,Conc_2,OD,OD_2) %>%
  filter(!is.na(ID)) %>%
  rowwise() %>%
  mutate(Conc_mean = mean(c(Conc,Conc_2),na.rm=T),
         Conc_sd = sd(c(Conc,Conc_2),na.rm=T),
         OD_mean = mean(c(OD,OD_2),na.rm=T),
         OD_sd = sd(c(OD,OD_2),na.rm=T)) %>%
  mutate(TEST_Conc_CV = 100*(Conc_sd/Conc_mean),
         TEST_Conc_CV = round(as.numeric(TEST_Conc_CV),3),
         TEST_OD_CV = 100*(OD_sd/OD_mean),
         TEST_OD_CV = round(as.numeric(TEST_OD_CV),3),
         SID = as.factor(round(as.numeric(ID),2))) %>%
  select(SID,TEST_Conc_CV,TEST_OD_CV) %>%
  filter(!SID == "0.1") %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID)) %>%
  filter(!is.na(SID)) %>%
  arrange(SID) 

Saliva_EST_CV_1 <- Saliva_EST_CV_1 %>% 
  rename(ID = Name,
         Conc = `[Concentration]`,
         OD = `450`) %>%
  mutate(Conc = as.numeric(Conc),
         OD = as.numeric(OD),
         Conc_2 = lead(Conc),
         OD_2 = lead(OD)) %>% 
  select(ID,Conc,Conc_2,OD,OD_2) %>%
  filter(!is.na(ID)) %>%
  rowwise() %>%
  mutate(Conc_mean = mean(c(Conc,Conc_2),na.rm=T),
         Conc_sd = sd(c(Conc,Conc_2),na.rm=T),
         OD_mean = mean(c(OD,OD_2),na.rm=T),
         OD_sd = sd(c(OD,OD_2),na.rm=T)) %>%
  mutate(EST_Conc_CV = 100*(Conc_sd/Conc_mean),
         EST_Conc_CV = round(as.numeric(EST_Conc_CV),3),
         EST_OD_CV = 100*(OD_sd/OD_mean),
         EST_OD_CV = round(as.numeric(EST_OD_CV),3),
         SID = as.factor(round(as.numeric(ID),2))) %>%
  select(SID,EST_Conc_CV,EST_OD_CV) %>%
  filter(!SID == "0.1") %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID)) %>%
  filter(!is.na(SID)) %>%
  arrange(SID) 

#batch 2
#import files
Saliva_DHEA_CV_2 <- read_xlsx(paste0(saliva_dir,'/TAG_MasterSheet_Saliva_2ndRun.xlsx'), sheet=5)
Saliva_TEST_CV_2 <- read_xlsx(paste0(saliva_dir,'/TAG_MasterSheet_Saliva_2ndRun.xlsx'), sheet=3)
Saliva_EST_CV_2 <- read_xlsx(paste0(saliva_dir,'/TAG_MasterSheet_Saliva_2ndRun.xlsx'), sheet=1)

#clean and calculate interassay CV for concentrations and optical densities
Saliva_DHEA_CV_2 <- Saliva_DHEA_CV_2 %>%
  rename(ID = Name,
         Conc = `[Concentration]`,
         OD = `450`) %>%
  filter(!(rerun=="R" & ID=="200.1")) %>%
  filter(!(rerun=="R" & ID=="207.4")) %>% 
  mutate(Conc = as.numeric(Conc),
         OD = as.numeric(OD),
         Conc_2 = lead(Conc),
         OD_2 = lead(OD)) %>% 
  select(ID,Conc,Conc_2,OD,OD_2) %>%
  filter(!is.na(ID)) %>%
  rowwise() %>%
  mutate(Conc_mean = mean(c(Conc,Conc_2),na.rm=T),
         Conc_sd = sd(c(Conc,Conc_2),na.rm=T),
         OD_mean = mean(c(OD,OD_2),na.rm=T),
         OD_sd = sd(c(OD,OD_2),na.rm=T)) %>%
  mutate(DHEA_Conc_CV = 100*(Conc_sd/Conc_mean),
         DHEA_Conc_CV = round(as.numeric(DHEA_Conc_CV),3),
         DHEA_OD_CV = 100*(OD_sd/OD_mean),
         DHEA_OD_CV = round(as.numeric(DHEA_OD_CV),3),
         SID = as.factor(round(as.numeric(ID),2))) %>%
  select(SID,DHEA_Conc_CV,DHEA_OD_CV) %>%
  filter(!is.na(SID)) %>%
  filter(!SID == "0.1") %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID)) %>%
  arrange(SID) 

Saliva_TEST_CV_2 <- Saliva_TEST_CV_2 %>% 
  rename(ID = Name,
         Conc = `[Concentration]`,
         OD = `450`) %>%
  mutate(Conc = as.numeric(Conc),
         OD = as.numeric(OD),
         Conc_2 = lead(Conc),
         OD_2 = lead(OD)) %>% 
  select(ID,Conc,Conc_2,OD,OD_2) %>%
  filter(!is.na(ID)) %>%
  rowwise() %>%
  mutate(Conc_mean = mean(c(Conc,Conc_2),na.rm=T),
         Conc_sd = sd(c(Conc,Conc_2),na.rm=T),
         OD_mean = mean(c(OD,OD_2),na.rm=T),
         OD_sd = sd(c(OD,OD_2),na.rm=T)) %>%
  mutate(TEST_Conc_CV = 100*(Conc_sd/Conc_mean),
         TEST_Conc_CV = round(as.numeric(TEST_Conc_CV),3),
         TEST_OD_CV = 100*(OD_sd/OD_mean),
         TEST_OD_CV = round(as.numeric(TEST_OD_CV),3),
         SID = as.factor(round(as.numeric(ID),2))) %>%
  select(SID,TEST_Conc_CV,TEST_OD_CV) %>%
  filter(!SID == "0.1") %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID)) %>%
  filter(!is.na(SID)) %>%
  arrange(SID) 

Saliva_EST_CV_2 <- Saliva_EST_CV_2 %>% 
  rename(ID = Name,
         Conc = `[Concentration]`,
         OD = `450`) %>%
  mutate(Conc = as.numeric(Conc),
         OD = as.numeric(OD),
         Conc_2 = lead(Conc),
         OD_2 = lead(OD)) %>% 
  select(ID,Conc,Conc_2,OD,OD_2) %>%
  filter(!is.na(ID)) %>%
  rowwise() %>%
  mutate(Conc_mean = mean(c(Conc,Conc_2),na.rm=T),
         Conc_sd = sd(c(Conc,Conc_2),na.rm=T),
         OD_mean = mean(c(OD,OD_2),na.rm=T),
         OD_sd = sd(c(OD,OD_2),na.rm=T)) %>%
  mutate(EST_Conc_CV = 100*(Conc_sd/Conc_mean),
         EST_Conc_CV = round(as.numeric(EST_Conc_CV),3),
         EST_OD_CV = 100*(OD_sd/OD_mean),
         EST_OD_CV = round(as.numeric(EST_OD_CV),3),
         SID = as.factor(round(as.numeric(ID),2))) %>%
  select(SID,EST_Conc_CV,EST_OD_CV) %>%
  filter(!SID == "0.1") %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID)) %>%
  filter(!is.na(SID)) %>%
  arrange(SID) 

#combine two batches and create master df
Saliva_DHEA_CV <- rbind(Saliva_DHEA_CV_1,Saliva_DHEA_CV_2)
Saliva_TEST_CV <- rbind(Saliva_TEST_CV_1,Saliva_TEST_CV_2)
Saliva_EST_CV <- rbind(Saliva_EST_CV_1,Saliva_EST_CV_2)

#deal with reruns
DHEA_reruns <- read_xlsx('~/Desktop/Saliva_repeats.xlsx', sheet=1)
TEST_reruns <- read_xlsx('~/Desktop/Saliva_repeats.xlsx', sheet=2)
EST_reruns <- read_xlsx('~/Desktop/Saliva_repeats.xlsx', sheet=3)

DHEA_reruns <- DHEA_reruns %>% 
  separate(ID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID)) %>%
  arrange(SID) %>%
  filter(!is.na(SID)) %>%
  select(SID,week,Notes,finalConc_CV,finalOD_CV) %>%
  mutate(rerun=as.numeric(1))

TEST_reruns <- TEST_reruns %>% 
  separate(ID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID)) %>%
  arrange(SID) %>%
  filter(!is.na(SID)) %>%
  select(SID,week,Notes,finalConc_CV,finalOD_CV) %>%
  mutate(rerun=as.numeric(1))

EST_reruns <- EST_reruns %>% 
  separate(ID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID)) %>%
  arrange(SID) %>%
  filter(!is.na(SID)) %>%
  select(SID,week,Notes,finalConc_CV,finalOD_CV) %>%
  mutate(rerun=as.numeric(1))

Saliva_DHEA_CV <- Saliva_DHEA_CV %>%
  left_join(., DHEA_reruns, by=c("SID","week")) %>%
  mutate(DHEA_Conc_CV = ifelse(!is.na(rerun),finalConc_CV,DHEA_Conc_CV),
         DHEA_OD_CV = ifelse(!is.na(rerun),finalOD_CV,DHEA_OD_CV)) %>%
  select(SID,week,DHEA_Conc_CV,DHEA_OD_CV)

Saliva_TEST_CV <- Saliva_TEST_CV %>%
  left_join(., TEST_reruns, by=c("SID","week")) %>%
  mutate(TEST_Conc_CV = ifelse(!is.na(rerun),finalConc_CV,TEST_Conc_CV),
         TEST_OD_CV = ifelse(!is.na(rerun),finalOD_CV,TEST_OD_CV)) %>%
  select(SID,week,TEST_Conc_CV,TEST_OD_CV)

Saliva_EST_CV <- Saliva_EST_CV %>%
  left_join(., EST_reruns, by=c("SID","week")) %>%
  mutate(EST_Conc_CV = ifelse(!is.na(rerun),finalConc_CV,EST_Conc_CV),
         EST_OD_CV = ifelse(!is.na(rerun),finalOD_CV,EST_OD_CV)) %>%
  select(SID,week,EST_Conc_CV,EST_OD_CV)

#creater master df
Saliva_CV <- Saliva_DHEA_CV %>% full_join(.,Saliva_TEST_CV) %>% 
  full_join(.,Saliva_EST_CV) %>% arrange(SID) %>% 
  filter(SID %in% overview$SID) %>%
  mutate(ID = paste0(SID,'_',week))

#identify any further problematic IDs (i.e. appear twice in dataframe)
probIDs <- Saliva_CV$ID[duplicated(Saliva_CV$ID)]
probDF <- Saliva_CV %>% filter(ID %in% probIDs) %>% arrange(ID)

#make sure that all duplicated rows are identical
check <- duplicated(probDF) | duplicated(probDF[nrow(probDF):1, ])[nrow(probDF):1]

#remove duplicated rows
Saliva_CV <- Saliva_CV[!duplicated(Saliva_CV$ID),]

#create long format master df
Saliva_CV_long <- Saliva_CV %>%
  gather(variable,value,DHEA_Conc_CV:EST_OD_CV,-SID,-week) %>%
  separate(variable, into=c("hormone","variable"), by="_") %>%
  spread(variable, value) %>%
  mutate(Conc = as.numeric(Conc),
         OD = as.numeric(OD))

#summarise intra-assay CVs
Saliva_CV_summary <- Saliva_CV_long %>% 
  group_by(hormone) %>%
  summarise(mean_ConcCV = mean(Conc,na.rm=T),
            sd_ConcCV = sd(Conc,na.rm=T),
            min_ConcCV = min(Conc,na.rm=T),
            max_ConcCV = max(Conc,na.rm=T),
            mean_odCV = mean(OD,na.rm=T),
            sd_odCV = sd(OD,na.rm=T),
            min_odCV = min(OD,na.rm=T),
            max_odCV = max(OD,na.rm=T))

#plot distribution of intra-assay CVs
ConcCV_plot <- Saliva_CV_long %>% 
  ggplot(aes(x = Conc)) +
  geom_histogram(color="black",fill="white") +
  facet_wrap(~ hormone, scales="free")

ConcCV_plot

odCV_plot <- Saliva_CV_long %>% filter(OD < 100) %>%
  ggplot(aes(x = OD)) +
  geom_histogram(color="black",fill="white") +
  facet_wrap(~ hormone, scales="free")

odCV_plot
```

###CALCULATE INTER-ASSAY CVS
```{r}

#import file of highs and lows
Saliva_DHEA_interCV <- read_xlsx(paste0(saliva_dir,'/TAG_W1_Saliva_HighsLows_interassayCV.xlsx'), sheet=1)
Saliva_TEST_interCV <- read_xlsx(paste0(saliva_dir,'/TAG_W1_Saliva_HighsLows_interassayCV.xlsx'), sheet=2)
Saliva_EST_interCV <- read_xlsx(paste0(saliva_dir,'/TAG_W1_Saliva_HighsLows_interassayCV.xlsx'), sheet=3)

#clean and calculate interassay CV for concentrations and optical densities
Saliva_DHEA_interCV <- Saliva_DHEA_interCV %>% 
  rename(ID = `Well ID`,
         Conc = `[Concentration]`,
         OD = `450`) %>%
  mutate(Conc = as.numeric(Conc),
         OD = as.numeric(OD),
         Conc_2 = lead(Conc),
         OD_2 = lead(OD)) %>% 
  filter(!is.na(ID)) %>%
  select(ID,Conc,Conc_2,OD,OD_2) %>%
  rowwise() %>%
  mutate(Conc_mean = mean(c(Conc,Conc_2),na.rm=T),
         OD_mean = mean(c(OD,OD_2),na.rm=T)) %>%
  group_by(ID) %>%
  summarise(ConcCV_mean = mean(Conc_mean),
            ConcCV_sd = sd(Conc_mean),
            ConcCV = 100*(ConcCV_sd/ConcCV_mean),
            odCV_mean = mean(OD_mean),
            odCV_sd = sd(OD_mean),
            odCV = 100*(odCV_sd/odCV_mean)) %>%
  group_by() %>%
  summarise(ConcCV = mean(ConcCV),
            odCV = mean(odCV))

Saliva_TEST_interCV <- Saliva_TEST_interCV %>% 
  rename(ID = `Well ID`,
         Conc = `[Concentration]`,
         OD = `450`) %>%
  mutate(Conc = as.numeric(Conc),
         OD = as.numeric(OD),
         Conc_2 = lead(Conc),
         OD_2 = lead(OD)) %>% 
  filter(!is.na(ID)) %>%
  select(ID,Conc,Conc_2,OD,OD_2) %>%
  rowwise() %>%
  mutate(Conc_mean = mean(c(Conc,Conc_2),na.rm=T),
         OD_mean = mean(c(OD,OD_2),na.rm=T)) %>%
  group_by(ID) %>%
  summarise(ConcCV_mean = mean(Conc_mean),
            ConcCV_sd = sd(Conc_mean),
            ConcCV = 100*(ConcCV_sd/ConcCV_mean),
            odCV_mean = mean(OD_mean),
            odCV_sd = sd(OD_mean),
            odCV = 100*(odCV_sd/odCV_mean)) %>%
  group_by() %>%
  summarise(ConcCV = mean(ConcCV),
            odCV = mean(odCV))

Saliva_EST_interCV <- Saliva_EST_interCV %>% 
  rename(ID = `Well ID`,
         Conc = `[Concentration]`,
         OD = `450`) %>%
  mutate(Conc = as.numeric(Conc),
         OD = as.numeric(OD),
         Conc_2 = lead(Conc),
         OD_2 = lead(OD)) %>% 
  filter(!is.na(ID)) %>%
  select(ID,Conc,Conc_2,OD,OD_2) %>%
  rowwise() %>%
  mutate(Conc_mean = mean(c(Conc,Conc_2),na.rm=T),
         OD_mean = mean(c(OD,OD_2),na.rm=T)) %>%
  group_by(ID) %>%
  summarise(ConcCV_mean = mean(Conc_mean,na.rm=T),
            ConcCV_sd = sd(Conc_mean,na.rm=T),
            ConcCV = 100*(ConcCV_sd/ConcCV_mean),
            odCV_mean = mean(OD_mean),
            odCV_sd = sd(OD_mean),
            odCV = 100*(odCV_sd/odCV_mean)) %>%
  group_by() %>%
  summarise(ConcCV = mean(ConcCV),
            odCV = mean(odCV))
```
