---
title: "cleaning Saliva hormones"
author: "Nandi"
date: "9 May 2018"
output: html_document
---

```{r, include=FALSE}
#LOAD PACKAGES AND SET DIRECTORIES

packages <- c("ggplot2","tidyr","stringr","knitr","corrplot","data.table","readxl","gridExtra","dplyr", "psych","kableExtra","lavaan")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)

cas_dir <- '/Volumes/psych-cog/dsnlab/TAG/'
saliva_dir <- paste0(cas_dir,'behavior/Saliva/Wave1')
options(digits=3)

in_dir <- '~/Downloads/' #to be updated once Saliva Overview Doc is finished.
```

###IMPORT "FINAL" SALIVA CONCENTRATIONS
```{r, echo=FALSE, message=FALSE, warning=FALSE, results="asis", fig.height=4, fig.width=4}
###IMPORT & CLEAN CONCENTRATIONS 
#import dataframe for each hormone, create SID as 3 digit numeric factor (i.e. "001"), combine all three hormones in one dataframe. 
Sal_DHEA <- read_xlsx(paste0(saliva_dir,'/TAG_SALIVA_Master_File.xlsx'), sheet=4)
Sal_TEST <- read_xlsx(paste0(saliva_dir,'/TAG_SALIVA_Master_File.xlsx'), sheet=8)
Sal_EST <- read_xlsx(paste0(saliva_dir,'/TAG_SALIVA_Master_File.xlsx'), sheet=12)

Sal_DHEA <- Sal_DHEA %>% 
  mutate(Concentration = ifelse(Concentration =='?????',1,Concentration)) %>%
  mutate(SID = as.factor(round(as.numeric(ID),2)),
         sal_DHEA = round(as.numeric(Concentration),3)) %>%
  select(SID,sal_DHEA) %>%
  replace_na(list(sal_DHEA = "missing")) %>%
  filter(!is.na(SID)) %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID),
         week = as.factor(week))

Sal_TEST <- Sal_TEST %>% 
  mutate(Concentration = ifelse(Concentration =='?????',4,Concentration)) %>%
  mutate(SID = as.factor(round(as.numeric(ID),2)),
         sal_TEST = round(as.numeric(Concentration),3)) %>%
  select(SID,sal_TEST) %>%
  replace_na(list(sal_TEST = "missing")) %>%
  filter(!is.na(SID)) %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID),
         week = as.factor(week))

Sal_EST <- Sal_EST %>% 
  mutate(Concentration = ifelse(Concentration =='?????',0.1,Concentration)) %>%
  mutate(SID = as.factor(round(as.numeric(ID),2)),
         sal_EST = round(as.numeric(Concentration),3)) %>%
  select(SID,sal_EST) %>%
  replace_na(list(sal_EST = "missing")) %>%
  filter(!is.na(SID)) %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID),
         week = as.factor(week))

Saliva <- Sal_DHEA %>% full_join(.,Sal_TEST) %>% full_join(.,Sal_EST) %>%
  mutate(ID = paste(SID,week,sep="_"))
```

###IMPORT SALIVA CVS
```{r, echo=FALSE, message=FALSE, warning=FALSE, results="asis", fig.height=4, fig.width=4}
Sal_DHEA_CV <- read_xlsx(paste0(saliva_dir,'/TAG_SALIVA_Master_File.xlsx'), sheet=1)
Sal_TEST_CV <- read_xlsx(paste0(saliva_dir,'/TAG_SALIVA_Master_File.xlsx'), sheet=5)
Sal_EST_CV <- read_xlsx(paste0(saliva_dir,'/TAG_SALIVA_Master_File.xlsx'), sheet=9)

Sal_DHEA_CV <- Sal_DHEA_CV %>% 
  filter(!is.na(Name)) %>%
  select(Name,`CV (%)`) %>%
  rename(ID = Name,
         DHEA_CV = `CV (%)`) %>%
  mutate(SID = as.factor(round(as.numeric(ID),2)),
         DHEA_CV = round(as.numeric(DHEA_CV),3)) %>%
  select(SID,DHEA_CV) %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID),
         week = as.factor(week)) %>%
  filter(!is.na(SID))

Sal_TEST_CV <- Sal_TEST_CV %>% 
  filter(!is.na(Name)) %>%
  select(Name,`CV (%)`) %>%
  rename(ID = Name,
         TEST_CV = `CV (%)`) %>%
  mutate(SID = as.factor(round(as.numeric(ID),2)),
         TEST_CV = round(as.numeric(TEST_CV),3)) %>%
  select(SID,TEST_CV) %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID),
         week = as.factor(week)) %>%
  filter(!is.na(SID))

Sal_EST_CV <- Sal_EST_CV %>% 
  filter(!is.na(Name)) %>%
  select(Name,`CV (%)`) %>%
  rename(ID = Name,
         EST_CV = `CV (%)`) %>%
  mutate(SID = as.factor(round(as.numeric(ID),2)),
         EST_CV = round(as.numeric(EST_CV),3)) %>%
  select(SID,EST_CV) %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID),
         week = as.factor(week)) %>%
  filter(!is.na(SID))

Saliva_CV <- Sal_DHEA_CV %>% full_join(.,Sal_TEST_CV) %>% full_join(.,Sal_EST_CV) %>%
  mutate(ID = paste(SID,week,sep="_"))
```

###IMPORT SALIVA REPLICATES
```{r, echo=FALSE, message=FALSE, warning=FALSE, results="asis", fig.height=4, fig.width=4}

Sal_DHEA_CV_rep <- read_xlsx(paste0(saliva_dir,'/TAG_SALIVA_Master_File.xlsx'), sheet=3)
Sal_TEST_CV_rep <- read_xlsx(paste0(saliva_dir,'/TAG_SALIVA_Master_File.xlsx'), sheet=7)
Sal_EST_CV_rep <- read_xlsx(paste0(saliva_dir,'/TAG_SALIVA_Master_File.xlsx'), sheet=11)

Sal_DHEA_CV_rep <- Sal_DHEA_CV_rep %>%
  rename(SID = Name,
         rep1 = TAG_2017.07.18_DHEA_Yoojin.xlsx,
         rep2 = X__1,
         CV2 = X__2,
         notes = X__3) %>%
  mutate(rep1 = as.numeric(rep1)) %>%
  filter(!is.na(rep1)) %>%
  mutate(SID = as.factor(round(as.numeric(SID),2))) %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID),
         week = as.factor(week)) %>%
  filter(!(SID == "Name"))

Sal_TEST_CV_rep <- Sal_TEST_CV_rep %>% 
  rename(SID = Name,
         rep1 = tag_06.18.2017_testo_tray2_ellen.xlsx,
         rep2 = X__1,
         CV2 = X__2,
         notes = X__3) %>%
  mutate(rep1 = as.numeric(rep1)) %>%
  filter(!is.na(rep1)) %>%
  mutate(SID = as.factor(round(as.numeric(SID),2))) %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID),
         week = as.factor(week)) %>%
  filter(!(SID == "Name"))

Sal_EST_CV_rep <- Sal_EST_CV_rep %>% 
  rename(SID = Name,
         rep1 = TAG_06.18.2017_Estradiol_Tray2_Olivia.xlsx,
         rep2 = X__1,
         CV2 = X__2,
         notes = X__3) %>%
  mutate(rep1 = as.numeric(rep1)) %>%
  filter(!is.na(rep1)) %>%
  mutate(SID = as.factor(round(as.numeric(SID),2))) %>%
  separate(SID, into =c("SID","week")) %>%
  mutate(SID = str_pad(SID, 3, pad = "0")) %>%
  mutate(SID = as.factor(SID),
         week = as.factor(week)) %>%
  filter(!(SID == "Name"))
```

###DISTRIBUTIONS OF CONCENTRATIONS
```{r, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
Saliva_long <- gather(Saliva, hormone, concentration, c(sal_DHEA,sal_TEST,sal_EST), factor_key=TRUE)

Saliva_long <- Saliva_long %>% 
  mutate(missing = if_else(concentration == "missing",1,0))

Saliva_long <- Saliva_long %>%
  mutate(concentration = as.numeric(concentration))

hist(subset(Saliva_long, hormone == "sal_DHEA")$concentration, main="", xlab="DHEA")
#abline(v=600,col="red")
writeLines("\n")
hist(subset(Saliva_long, hormone == "sal_TEST")$concentration, main="", xlab="TEST")
#abline(v=200,col="red")
writeLines("\n")
hist(subset(Saliva_long, hormone == "sal_EST")$concentration, main="", xlab="EST")
#abline(v=3,col="red")
writeLines("\n")
```

###DISTRIBUTIONS OF ICV
```{r, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
DHEA_CV<-ggplot(Saliva_CV, aes(x=DHEA_CV)) +
  geom_histogram(color="black",fill="white")
# + geom_vline(xintercept=30,linetype="dashed",colour="red")
DHEA_CV
DHEA_CV_exc <- Saliva_CV %>% filter(DHEA_CV > 30) %>% select(ID)

TEST_CV<-ggplot(Saliva_CV, aes(x=TEST_CV)) +
  geom_histogram(color="black",fill="white")
# + geom_vline(xintercept=30,linetype="dashed",colour="red")
TEST_CV
TEST_CV_exc <- Saliva_CV %>% filter(TEST_CV > 30) %>% select(ID)

EST_CV<-ggplot(Saliva_CV, aes(x=EST_CV)) +
  geom_histogram(color="black",fill="white")
# + geom_vline(xintercept=30,linetype="dashed",colour="red")
EST_CV
EST_CV_exc <- Saliva_CV %>% filter(EST_CV > 30) %>% select(ID)
```

