---
title: "Resting State Stats"
author: "Kate"
date: "26 April 2017"
output: html_document
---

# Begin script

Load required packages
```{r Load Required Packages, message=FALSE, warning=FALSE, include=FALSE}
## Load required packages ##
packages <-  c("lme4", "nlme", "ggplot2", "zoo","dplyr", "tidyr", "knitr",
              "parallel", "data.table", "lubridate")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)
```

Set graph/plot options
```{r}
theme_kate <- function () { 
    theme_bw() +
  theme_minimal(base_size = 14, base_family = "Avenir") +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        legend.position="none")
}

resave_plots=FALSE

heatmap_color_palette <- colorRampPalette(c("#fde0dd", "#fa9fb5", "#c51b8a"))

group_labels<-c("community"='Community', 
                "foster"="Child Welfare Services")

colour_labels=c("#fa9fb5", "#ae017e")

purple_colours=c("#bcbddc","#756bb1","#54278f")

group_colors <- c("community" = "#fa9fb5", "foster" = "#ae017e")
```

Extract Resting state preprocessing stats
```{r Extract and plot run times, echo=TRUE}
scrubbingThreshold<-.2
# Set directory
rsfcMRI_subjects="/Volumes/psych-cog/dsnlab/TAG/TAG_BIDS/derivatives/rsfMRI_preproc_noFDscrub/"
# create sub list based on folders within the resting state subjects folder
subs<-list.files(path = rsfcMRI_subjects, pattern = "sub")
# extract info


alignmentissues=function(sub){
  if (file.exists(paste0(rsfcMRI_subjects,sub,"/",sub,".results/out.ss_review.",sub,".txt"))){
      alignment<-(read.csv(paste0(rsfcMRI_subjects,sub,"/",sub,".results/out.ss_review.",sub,".txt")) %>%
                    filter(grepl("anat/EPI",.[[1]])))
      alignment<-(as.numeric(substring(as.character(alignment[[1]][1]),29,36)))
      } else {
        alignment<-NA
      }
  cbind(sub,alignment)
}
alignmentout<-lapply(subs,alignmentissues                     )
alignmentout.df<-as.data.frame(do.call(rbind,alignmentout))



extract_rsfcMRI_runinfo= function(sub){
if (file.exists(paste0(rsfcMRI_subjects,sub,"/",sub,".results/motion_",sub,"_enorm.1D"))){
      log<-read.csv(paste0(rsfcMRI_subjects,sub,"/",sub,".results/motion_",sub,"_enorm.1D"))
      preproc_complete="yes"
      blurps<-nrow(log %>% filter(.[[1]]>scrubbingThreshold))
      potential<-(nrow(log)-(blurps*2))
      viable<-ifelse(potential>=385,"yes","no")
      cbind(sub,blurps,potential,viable,preproc_complete)
    } else{
      preproc_complete="no"
      blurps<-NA
      potential<-NA
      viable<-"no"
      cbind(sub,blurps,potential,viable,preproc_complete)
      }
}
outputlist<-lapply(subs,extract_rsfcMRI_runinfo)
output.df<-as.data.frame(do.call(rbind,outputlist)) %>% 
  mutate(blurps=as.numeric(levels(blurps))[blurps],
         potential=as.numeric(levels(potential))[potential]) %>%
  mutate(potential=ifelse(potential<0,0,potential))

useable <- ggplot((output.df %>% select(-blurps)),
                aes(x=sub, y=(potential*.78)/60, fill=viable))
useable + geom_bar(colour="black", stat="identity") 

sublist<-output.df %>%
  mutate(sub=as.character(sub)) %>%
  filter(!is.na(potential)) %>%
  select(sub)
print(paste0(nrow(output.df%>%filter(viable=="yes"))," are viable"))
```

