---
title: "Create func cohort file"
author: "Theresa Cheng"
date: "June 6, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages
packages <- c("ggplot2", "tidyverse", "stringr", "knitr", "rio", "snakecase")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)

# Set inputs
data_dir <- '/projects/dsnlab/shared/tag/fmriprep_20.2.1/fmriprep'
inclusion_info_dir <-'/home/tcheng/xcpengine/data/'
inclusion_info_file <- 'rsfc_inclusion.csv'
inclusion_info_three_runs_file <- 'rsfc_inclusion_three_runs.csv'
output_dir <- '/projects/dsnlab/shared/tag/fmriprep_20.2.1/fmriprep/derivatives'

# write tcat subjects list
tcat_dir <- '/projects/dsnlab/shared/tag/TAG_scripts/rsfMRI/cheng_spf/tcat'

# extract timecourses subject list
timecourses_dir <- '/projects/dsnlab/shared/tag/TAG_scripts/rsfMRI/cheng_spf/timecourses'

```

```{r read in and clean subject list}

inclusion_info <- import(paste0(inclusion_info_dir, inclusion_info_file))
inclusion_info <- inclusion_info %>% 
  filter(!is.na(wave)) # remove extra lines 
inclusion_info$exclude_rs_w1 <- ifelse(is.na(inclusion_info$exclude_rs_w1), 0, inclusion_info$exclude_rs_w1) # fill in NAs with zeros
inclusion_info$tag_id <- inclusion_info$subject_id # duplicate and reformat subject IDs
inclusion_info$subject_id <- paste0(unlist(lapply(str_split(inclusion_info$subject_id, "TAG"), function(x){x[2]})), "w0", inclusion_info$wave)

inclusion_info_three_runs <- import(paste0(inclusion_info_dir, inclusion_info_three_runs_file))
```

```{r obtain confounds dataset}

rerun_confounds = FALSE

if (rerun_confounds == TRUE){
  # Source config file from auto-motion-fmriprep
  source('/projects/dsnlab/shared/tag/TAG_scripts/fMRI/fx/motion/auto-motion-fmriprep-20210518/config.R')
  
  dataset = data.frame()
  columnNames = c("subjectID", "wave", "task", "run", "volume", "CSF", "WhiteMatter", 
                "GlobalSignal", "stdDVARS", "non.stdDVARS", "vx.wisestdDVARS", 
                "FramewiseDisplacement", "tCompCor00", "tCompCor01", "tCompCor02", 
                "tCompCor03", "tCompCor04", "tCompCor05", "aCompCor00", "aCompCor01", 
                "aCompCor02", "aCompCor03", "aCompCor04", "aCompCor05", "Cosine00", 
                "X", "Y", "Z", "RotX", "RotY", "RotZ")
  
  fileRegex = '.*func/sub-(.*)_ses-(.*)_task-(.*)_run-(.*)_desc-.*.tsv'
  fileVars = c('subjectID', 'wave', 'task', 'run')
  
  fileList = list.files(data_dir, pattern = '.*rest.*confounds.*.tsv', recursive = TRUE)
  
    for (file in fileList) {

      tmp = tryCatch(read_tsv(file.path(confoundDir, file)) %>%
                       setNames(snakecase::to_upper_camel_case(names(.))) %>%
                       setNames(gsub("AComp", "aComp", names(.))) %>%
                       setNames(gsub("TComp", "tComp", names(.))) %>%
                       setNames(gsub("Trans", "", names(.))) %>%
                       mutate(file = ifelse(!grepl("ses", file), gsub("task", "ses-1_task", file), file),
                              file = ifelse(!grepl("run", file), gsub("desc", "run-1_desc", file), file)) %>%
                       extract(file, fileVars,
                               fileRegex) %>%
                       rename("CSF" = Csf,
                              "stdDVARS" = StdDvars,
                              "non.stdDVARS" = Dvars) %>%
                       mutate(run = str_extract(run, "[[:digit:]]+"),
                              run = as.integer(run),
                              volume = row_number()) %>%
                       mutate_if(is.character, list(~ ifelse(. == "n/a", 0, .))) %>%
                       mutate_at(vars(contains("DVARS"), contains("Framewise")), as.numeric), error = function(e) message(file))
    
    # add missing columns and select subset classifier columns
    missingColumns = setdiff(columnNames, names(tmp))
    tmp[missingColumns] = 0 
    
    tmp = tmp  %>%
      select(subjectID, wave, task, run, volume, CSF, WhiteMatter, 
             GlobalSignal, stdDVARS, non.stdDVARS, vx.wisestdDVARS, 
             FramewiseDisplacement, tCompCor00, tCompCor01, tCompCor02, 
             tCompCor03, tCompCor04, tCompCor05, aCompCor00, aCompCor01, 
             aCompCor02, aCompCor03, aCompCor04, aCompCor05, Cosine00, 
             X, Y, Z, RotX, RotY, RotZ)
    
    if (length(tmp) > 0) {
      dataset = bind_rows(dataset, tmp)
      rm(tmp)
    }
    }
} else {
    dataset <- readRDS(paste0(output_dir, "all_confound_info.rds"))
}
```

```{r remove extra runs}

for (i in 1:nrow(inclusion_info_three_runs)){ # for every row of the inclusion info three runs df, remove runs that should not be concatenated
  
  if (inclusion_info_three_runs$use_run1[i] == 0){ # if you're not supposed to use run1, filter out those subject's run 1s
    dataset <- filter(dataset, !(subjectID == paste0("TAG", inclusion_info_three_runs$subject_id[i]) & run == 1))
  } else if (inclusion_info_three_runs$use_run2[i] == 0){ # likewise for run2
    dataset <- filter(dataset, !(subjectID == paste0("TAG", inclusion_info_three_runs$subject_id[i]) & run == 2))
  } # note that no participants were not supposed to have run3
}
```

```{r}

dataset$FD_below_thresh <- ifelse(dataset$FramewiseDisplacement < 0.2, 1, 0)

enough_good_frames <- dataset %>% 
  group_by(subjectID) %>% 
  summarise(num_frames_below_thresh = sum(FD_below_thresh)) %>% 
  mutate(enough_good_frames = ifelse(num_frames_below_thresh >= 385, 1, 0), # five minutes of data 
         enough_good_frames_4min30s = ifelse(num_frames_below_thresh >= 347, 1, 0)) # 4 mins 30 seconds of data

temp <- filter(dataset, subjectID=="TAG077w02") %>% 
  group_by(run) %>% 
  summarise(num_frames_below_thresh = sum(FD_below_thresh))

enough_good_frames$subject_id = unlist(lapply(str_split(enough_good_frames$subjectID, "TAG"), function(x){x[2]}))

enough_good_frames_by_run <- dataset %>% 
  group_by(subjectID, run) %>% 
  summarise(num_frames_below_thresh = sum (FD_below_thresh))
inclusion_df <- full_join(inclusion_info, enough_good_frames, by = "subject_id")
inclusion_df$enough_good_frames <- replace_na(inclusion_df$enough_good_frames, 0)

inclusion_df <- inclusion_df %>% 
  select(subject_id, wave, exclude_rs_w1, rs1_use, rs2_use, num_frames_below_thresh, enough_good_frames, enough_good_frames_4min30s)

# add variable re: third run
inclusion_df$third_run <- ifelse(inclusion_df$subject_id %in% unique(inclusion_info_three_runs$subject_id), 1, 0)

# do some plots and basic stats re: subject inclusion
inclusion_df$wave <- as.factor(inclusion_df$wave)

ggplot(inclusion_df, aes(x = num_frames_below_thresh, fill = wave)) + 
  geom_histogram() +
  geom_vline(aes(xintercept = 385))+
  geom_vline (aes(xintercept = 347))

inclusion_df %>% 
  filter(exclude_rs_w1 != 1) %>% 
  group_by(wave) %>% 
  count(enough_good_frames_4min30s)

inclusion_df %>% 
  filter(exclude_rs_w1 == 0) %>% 
  group_by(wave) %>% 
  count(enough_good_frames)

# write.csv(inclusion_df, paste0(inclusion_info_dir, "rsfc_enough_frames.csv"))
```

```{r write subject list for concatenation, include = FALSE}

rerun_tcat = FALSE

if (rerun_tcat == TRUE) {

# target format: 001w01,wave1,run-1,run-2
tcat_subjects = data.frame(subject_id = as.character(),
                           wave = as.character(),
                           first_run = as.character(),
                           second_run = as.character())

# if the participant should have both runs included, then concatenate them
for (i in 1:nrow(inclusion_df)){
  
  if (inclusion_df$enough_good_frames[i] == 1 & inclusion_df$exclude_rs_w1[i] == 0 & inclusion_df$third_run[i] == 0){
    subject_id <- inclusion_df$subject_id[i]
    wave <- paste0("wave", inclusion_df$wave[i])
    
    tcat_subjects <-rbind(tcat_subjects,
                          data.frame(subject_id = subject_id,
                                     wave = wave,
                                     first_run = "run-1", 
                                     second_run = "run-2"))
  }
}

# third runs 
tcat_subjects_three_runs = data.frame(subject_id = as.character(),
                           wave = as.character(),
                           first_run = as.character(),
                           second_run = as.character())

for (i in 1:nrow(inclusion_info_three_runs)){
  
  temp_df <- filter(inclusion_df, subject_id == inclusion_info_three_runs$subject_id[i])
  subject_id <- temp_df$subject_id
  wave <- paste0("wave", temp_df$wave)
  
  if (temp_df$enough_good_frames == 1 & temp_df$exclude_rs_w1 == 0 & inclusion_info_three_runs$use_run1[i] == 1){
    tcat_subjects_three_runs <-rbind(tcat_subjects_three_runs,
                          data.frame(subject_id = subject_id,
                                     wave = wave,
                                     first_run = "run-1", 
                                     second_run = "run-3"))
    
  } else if (temp_df$enough_good_frames == 1 & temp_df$exclude_rs_w1 == 0 & inclusion_info_three_runs$use_run2[i] == 1){
    tcat_subjects_three_runs <-rbind(tcat_subjects_three_runs,
                          data.frame(subject_id = subject_id,
                                     wave = wave,
                                     first_run = "run-2", 
                                     second_run = "run-3"))
  }  
}

tcat_subjects <- rbind(tcat_subjects, tcat_subjects_three_runs)
#write.table(tcat_subjects, paste0(tcat_dir, "/tcat_subject_list.txt"), row.names = FALSE, quote = FALSE, sep = ",")
} else {
  tcat_subjects <- import(paste0(tcat_dir, "/tcat_subject_list.txt"))
}

```

```{r write func_cohort.csv file for xcp engine - CONCATENATED RUNS}

# if inclusion_df$enough_good_frames == 1 and inclusion_df$exclude_rs_w1 !=1
# then use assume both runs are available

func_cohort = data.frame(id0 = as.character(),
                         id1 = as.character(),
                         id2 = as.character(),
                         img = as.character())

for (i in 1:nrow(inclusion_df)){
  
  if (inclusion_df$enough_good_frames[i] == 1 & inclusion_df$exclude_rs_w1[i] == 0){
    id0 <- paste0("sub-TAG", inclusion_df$subject_id[i])
    id1 <- paste0("ses-wave", inclusion_df$wave[i])
    img <- paste0("fmriprep/", id0, "/", id1, "/func/tcat_", id0, "_", id1, "_task-rest_space-MNI152NLin2009cAsym.nii.gz")
    
    func_cohort <- rbind(func_cohort,
          data.frame(id0 = id0,
               id1 = id1,
               img = img))
    
  } else if (inclusion_df$enough_good_frames[i] == 1 & inclusion_df$exclude_rs_w1[i] == 1 & inclusion_df$rs1_use[i] == 1 & inclusion_df$third_run == 0){
    id0 <- paste0("sub-TAG", inclusion_df$subject_id[i])
    id1 <- paste0("ses-wave", inclusion_df$wave[i])
    img <- paste0("fmriprep/", id0, "/", id1, "/func/", id0, "_", id1, "_task-rest_run-1_space-MNI152NLin2009cAsym.nii.gz")
    
    func_cohort <- rbind(func_cohort,
                         data.frame(id0 = id0,
                                    id1 = id1,
                                    img = img))
    
  } else if (inclusion_df$enough_good_frames[i] == 1 & inclusion_df$exclude_rs_w1[i] == 1 & inclusion_df$rs2_use[i] == 1 & inclusion_df$third_run == 0){
    id0 <- paste0("sub-TAG", inclusion_df$subject_id[i])
    id1 <- paste0("ses-wave", inclusion_df$wave[i])
    img <- paste0("fmriprep/", id0, "/", id1, "/func/", id0, "_", id1, "_task-rest_run-2_space-MNI152NLin2009cAsym.nii.gz")
    
    func_cohort <- rbind(func_cohort,
                         data.frame(id0 = id0,
                                    id1 = id1,
                                    img = img))
  }
}


# write.table(func_cohort, paste0(inclusion_info_dir, "func_cohort_files/func_cohort_tag.csv"), row.names = FALSE, quote = FALSE, sep = ",")
```


```{r write func_cohort.csv file for xcp engine - SEPARATE RUNS, include = FALSE}

# if inclusion_df$enough_good_frames == 1 and inclusion_df$exclude_rs_w1 !=1
# then use assume both runs are available
func_cohort = data.frame(id0 = as.character(),
                         id1 = as.character(),
                         id2 = as.character(),
                         img = as.character())

for (i in 1:nrow(inclusion_df)){
  
  if (inclusion_df$enough_good_frames[i] == 1 & inclusion_df$exclude_rs_w1[i] == 0 & inclusion_df$third_run == 0){
    id0 <- paste0("sub-TAG", inclusion_df$subject_id[i])
    id1 <- paste0("ses-wave", inclusion_df$wave[i])
    img1 <- paste0("fmriprep/", id0, "/", id1, "/func/", id0, "_", id1, "_task-rest_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz")
    img2 <- paste0("fmriprep/", id0, "/", id1, "/func/", id0, "_", id1, "_task-rest_run-2_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz")
    
    func_cohort <- rbind(func_cohort,
          data.frame(id0 = rep(id0, 2),
               id1 = rep(id1, 2),
               id2 = c("run-1", "run-2"),
               img = c(img1, img2)))
  } else if (inclusion_df$enough_good_frames[i] == 1 & inclusion_df$exclude_rs_w1[i] == 1 & inclusion_df$rs1_use[i] == 1 & inclusion_df$third_run == 0){
    id0 <- paste0("sub-TAG", inclusion_df$subject_id[i])
    id1 <- paste0("ses-wave", inclusion_df$wave[i])
    img1 <- paste0("fmriprep/", id0, "/", id1, "/func/", id0, "_", id1, "_task-rest_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz")
    
    func_cohort <- rbind(func_cohort,
                         data.frame(id0 = id0,
                                    id1 = id1,
                                    id2 = "run-1",
                                    img = img1))
  } else if (inclusion_df$enough_good_frames[i] == 1 & inclusion_df$exclude_rs_w1[i] == 1 & inclusion_df$rs2_use[i] == 1 & inclusion_df$third_run == 0){
    id0 <- paste0("sub-TAG", inclusion_df$subject_id[i])
    id1 <- paste0("ses-wave", inclusion_df$wave[i])
    img2 <- paste0("fmriprep/", id0, "/", id1, "/func/", id0, "_", id1, "_task-rest_run-2_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz")
    
    func_cohort <- rbind(func_cohort,
                         data.frame(id0 = id0,
                                    id1 = id1,
                                    id2 = "run-2",
                                    img = img2))
  }
}


# third runs 
func_cohort_three_runs = data.frame(id0 = as.character(),
                         id1 = as.character(),
                         id2 = as.character(),
                         img = as.character())


for (i in 1:nrow(inclusion_info_three_runs)){
  
  temp_df <- filter(inclusion_df, subject_id == inclusion_info_three_runs$subject_id[i])
  
  if (temp_df$enough_good_frames == 1 & temp_df$exclude_rs_w1 == 0 & inclusion_info_three_runs$use_run1[i] == 1){
    id0 <- paste0("sub-TAG", temp_df$subject_id)
    id1 <- paste0("ses-wave", temp_df$wave)
    img1 <- paste0("fmriprep/", id0, "/", id1, "/func/", id0, "_", id1, "_task-rest_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz")
    img3 <- paste0("fmriprep/", id0, "/", id1, "/func/", id0, "_", id1, "_task-rest_run-3_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz")
    
    func_cohort_three_runs <- rbind(func_cohort_three_runs,
          data.frame(id0 = rep(id0, 2),
               id1 = rep(id1, 2),
               id2 = c("run-1", "run-3"),
               img = c(img1, img3)))
    
  } else if (temp_df$enough_good_frames == 1 & temp_df$exclude_rs_w1 == 0 & inclusion_info_three_runs$use_run2[i] == 1){
    id0 <- paste0("sub-TAG", temp_df$subject_id)
    id1 <- paste0("ses-wave", temp_df$wave)
    img2 <- paste0("fmriprep/", id0, "/", id1, "/func/", id0, "_", id1, "_task-rest_run-2_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz")
    img3 <- paste0("fmriprep/", id0, "/", id1, "/func/", id0, "_", id1, "_task-rest_run-3_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz")
    
    func_cohort_three_runs <- rbind(func_cohort_three_runs,
          data.frame(id0 = rep(id0, 2),
               id1 = rep(id1, 2),
               id2 = c("run-2", "run-3"),
               img = c(img2, img3)))
  }  
}

func_cohort <- rbind(func_cohort, func_cohort_three_runs)
#write.table(func_cohort, paste0(inclusion_info_dir, "func_cohort_files/func_cohort_tag.csv"), row.names = FALSE, quote = FALSE, sep = ",")

func_cohort <- import(paste0(inclusion_info_dir, "func_cohort_files/func_cohort_tag_single_runs.csv"))
```
