---
title: "auto-motion-fmriprep_classification"
author: "Nandi"
date: "25 June 2018"
output: html_document
---

# load packages & set paths
```{r}
osuRepo = 'http://ftp.osuosl.org/pub/cran/'

if(!require(caret)){
  install.packages('caret',repos=osuRepo)
}

scriptDir = '/Volumes/StorEDGE/WORK/DSN/TAG/TAG_scripts/fMRI/fx/motion/'
outputDir = '/Volumes/psych-cog/dsnlab/TAG/nonbids_data/fMRI/fx/motion/wave1/auto-motion-fmriprep/classification/'
plotDir = '/Volumes/psych-cog/dsnlab/TAG/nonbids_data/fMRI/fx/motion/wave1/auto-motion-fmriprep/classification/plots/'
```

#Load fmriprep & euc motion
```{r}
joined = read.csv(paste0(scriptDir,'output/all_motion.csv'), stringsAsFactors = FALSE)
```

# load hand coded data and merge everything
```{r}
coded = read.csv(paste0('~/Desktop/motionQC.csv'))
coded <- coded %>%
  extract(Run, c("task", "run"), "([A-Z]{3})([0-9]{1})") %>%
  mutate(run = as.integer(run),
         SID = as.integer(gsub("[^0-9\\.]", "", SID)),
         volume = Volume+1) %>%
  mutate(sub.run = paste(SID, task, run, sep = "_")) %>%
  mutate(manual_artifact = 1,
         manual_artifact = as.factor(manual_artifact))

sub_run = unique(coded$sub.run) #those who have been coded

joined = left_join(joined, coded, by = c("SID", "task", "run", "volume", "sub.run")) %>%
  filter(sub.run %in% sub_run) %>%
  select(SID, task, run, volume, artifact, artifact_N, manual_artifact, everything()) %>%
  mutate(manual_artifact=ifelse(is.na(manual_artifact),0,manual_artifact))
```

# calculate sensitivity and specificity 
```{r}
joined <- joined %>% mutate(artifact = as.factor(artifact),
                            artifact_N = as.factor(artifact_N),
                            manual_artifact = as.factor(manual_artifact))

# table of sensitivity and specificity
summaryDF <- joined %>% group_by() %>%
  summarise(sens_noNeighbor = sensitivity(artifact, manual_artifact, positive = levels(manual_artifact)[2]),
            sens_Neighbor = sensitivity(artifact_N, manual_artifact, positive = levels(manual_artifact)[2]),
            spec_noNeighbor = specificity(artifact, manual_artifact, negative = levels(manual_artifact)[1]),
            spec_Neighbor = specificity(artifact_N, manual_artifact, negative = levels(manual_artifact)[1])) %>%
  gather(measure,value) %>%
  mutate(variable = substr(measure, 1, 4),
         measure = substring(measure, 6)) %>%
  spread(variable,value)

write.csv(summaryDF,paste0(outputDir,'summary.csv'),row.names=F)
```

# visualize confounds on a subject level
```{r, fig.width = 12, fig.height = 15}
data.plot = joined %>%
  gather(feature, value, -c(SID, task, run, volume, manual_artifact))

features = c("eucTrans","eucRot","eucTransDer","eucRotDer","FramewiseDisplacement", "stdDVARS","artifact", "artifact_N")

data.sub = data.plot %>%
  filter(feature %in% features) %>%
  mutate(sort = ifelse(feature == "eucTrans", 1,
                ifelse(feature == "eucRot", 2,
                ifelse(feature == "eucTransDer", 3,
                ifelse(feature == "eucRotDer", 4, 
                ifelse(feature == "FramewiseDisplacement", 5,
                ifelse(feature == "stdDVARS", 6,
                ifelse(feature == "artifact", 7, 
                ifelse(feature == "artifact_N", 8, NA))))))))) %>%
  mutate(value=round(as.numeric(value),1),
         task=paste0(task,run),
         manual_artifact=as.factor(manual_artifact))

nada = data.sub %>% 
  group_by(SID,task) %>%
    do({
      plot = ggplot(., aes(volume, value)) + 
        geom_point(aes(color = manual_artifact)) +
        scale_color_manual(values = c("0"="grey", "1"="blue")) +
        geom_line(size = .25, show.legend = FALSE) +
        facet_wrap(task ~ reorder(feature,sort), ncol = 4, scales = "free") +
        labs(title = .$SID[[1]])
      print(plot)
      ggsave(plot, file = paste0(plotDir,.$SID[[1]],"_",.$task[[1]],'.pdf'), height = 5, width = 12)
      data.frame()
    })
```



