---
title: "FreeSurfer Stats"
author: "Kate"
date: "26 April 2017"
output: html_document
---

# Begin script

Load required packages
```{r Load Required Packages, message=FALSE, warning=FALSE, include=FALSE}
## Load required packages ##
packages <-  c("lme4", "nlme", "ggplot2", "zoo","dplyr", "tidyr", "knitr",
              "parallel", "data.table", "lubridate")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)
```

Extract FreeSurfer preprocessing stats
```{r Extract and plot run times, echo=TRUE}
# Set directory
freesurfer_subjects="/Volumes/TDS/ppcd_nii/sMRI/subjects/"
# create sub list based on folders within the freesurfer subjects folder
subs<-list.files(path = freesurfer_subjects, pattern = "sub")
# extract info
extract_freesurfer_runinfo= function(sub){
  log<-read.csv(paste0(freesurfer_subjects,sub,"/scripts/recon-all-status.log"))
  finaloutput<-tail(log,1)
  recon_done<-read.csv(paste0(freesurfer_subjects,sub,"/scripts/recon-all.done"))
  runtime<-recon_done %>% filter(grepl("RUNTIME",.[[1]]))
  runtime<-as.character(runtime[[1]])
  runtime<-substring(runtime,first=15,last=(nchar(runtime)))
  cbind(sub,runtime,finaloutput)}
outputlist<-lapply(subs,extract_freesurfer_runinfo)
output.df<-as.data.frame(do.call(rbind,outputlist)) %>% 
  mutate(runtime=as.numeric(levels(runtime))[runtime])
times <- ggplot((output.df %>% select(-status.file.for.recon.all)),
                aes(x=sub, y=runtime, fill=runtime))
times + geom_bar(colour="black", stat="identity") 
```


Plot structural MRI info
```{r Extract and plot structural MRI info, echo=TRUE}
# Set directory
freesurfer_subjects="/Volumes/TDS/ppcd_nii/sMRI/subjects/"
# create sub list based on folders within the freesurfer subjects folder
subs<-list.files(path = freesurfer_subjects, pattern = "sub")
# extract info
asegcolnames<-c("Index","SegId","NVoxels","Volume_mm3","StructName","normMean","normStdDev","normMin","normMax","normRange")
extract_amygdala_vol= function(sub){
  aseg<-read.table(paste0(freesurfer_subjects,sub,"/stats/aseg.stats"))
  colnames(aseg)<-asegcolnames
  amygdala_vol<-aseg %>% filter(grepl("Left-Amygdala",StructName)) %>% select(Volume_mm3)
  cbind(sub,amygdala_vol)}
outputlist<-lapply(subs,extract_amygdala_vol)
output.df<-as.data.frame(do.call(rbind,outputlist)) %>% 
  mutate(amygdala_vol=Volume_mm3) %>% select (-Volume_mm3)
amygdala_volumes <- ggplot(output.df,aes(x=sub, y=amygdala_vol))
amygdala_volumes + geom_point()
```