---
title: "Nandi Network Workshop"
author: "Kate L. Mills & John C. Flournoy"
date: "June 28, 2017"
output: html_document
---

Load required packages
```{r Load Required Packages, message=FALSE, warning=FALSE, include=FALSE}
## Load required packages ##
packages <-  c("lme4", "nlme", "ggplot2", "zoo", "dplyr", "tidyr", "knitr",
              "parallel", "data.table", "lubridate")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)
```


Load behavioral data
```{r Behavior, message=FALSE, warning=FALSE, include=FALSE}
redcapData <- read.csv(paste0("/Volumes/psych-cog/dsnlab/TAG/behavior/Questionnaires/Confidential/redcap_dates.csv"), header = TRUE, stringsAsFactors = FALSE)
redcapData_dob<-redcapData %>%
  select(dob,subject_spit_id) %>%
  filter(!dob=="")
redcapData_sessiondates<-redcapData %>%
  select(sa_date,sb_date,subject_spit_id) %>%
  filter(!sa_date=="")
redcap_cleaned<-merge(redcapData_sessiondates,redcapData_dob) %>%
  mutate(tagid=substring(subject_spit_id,first=4,last=length(subject_spit_id)))%>%
  filter(!subject_spit_id=="TAG_001P") %>%
  mutate(tagid=ifelse(nchar(tagid)==4,substring(subject_spit_id,first=5,last=length(subject_spit_id)),tagid)) %>%
  mutate(tagid=sprintf("TAG%03d",as.integer(tagid))) %>%
  select(-subject_spit_id)
rm(redcapData_dob,redcapData,redcapData_sessiondates)
```

Filter sublist
```{r}
sublist<-sublist %>%
  filter(!sub=="sub-TAG000") %>%
  mutate(sub=as.character(sub))
  
```

Get timecourses
```{r}
numcores<-detectCores()[1]
scrubbingThreshold<-.2
sub_base_dir="/Volumes/psych-cog/dsnlab/TAG/TAG_BIDS/derivatives/rsfMRI_preproc_noFDscrub/rsfMRI_preproc_noFDscrub/"
parcellation_list_dir='/projects/dsnlab/tag/TAG_scripts/sMRI/templates/lists/'
gordon_lhparcels<-as.data.frame(read.table(paste0(parcellation_list_dir,"lhlabels.txt"))[[1]]) %>%
  filter(grepl("lh.Parcel", .[[1]]))%>%
  mutate(parcel_name=.[[1]]) %>%
  select(parcel_name)
gordon_rhparcels<-as.data.frame(read.table(paste0(parcellation_list_dir,"rhlabels.txt"))[[1]]) %>%
  filter(grepl("rh.Parcel", .[[1]]))%>%
  mutate(parcel_name=.[[1]]) %>%
  select(parcel_name)
gordon<-bind_rows(gordon_rhparcels,gordon_lhparcels)

aparc_parcels<-as.data.frame(read.table(paste0(parcellation_list_dir,"aparcrois.txt"))[[1]]) %>%
  mutate(parcel_name=.[[1]]) %>%
  select(parcel_name)
  
collectAndCorTimecourses <- function(sub, parcels, scrubbingThreshold, sub_base_dir) {
  #below makes a df with every parcel file location, that then reads in the data from that parcel.
  #result is a long data frame with indexes within each parcel (e.g. volume number 1:514)
  timecourses <- data.frame(file_location=paste0(sub_base_dir,sub,"/",sub,".results/timecourses/",sub,'_',parcels$parcel_name,'.txt'),
                            sub=sub,
                            parcel=parcels$parcel_name,
                            stringsAsFactors=F) %>%
    group_by(sub,parcel) %>% do({
      timecourse<-try(fread(.$file_location, stringsAsFactors=F))
      if('try-error' %in% class(timecourse)) timecourse <- data.frame(NA)
      timecourse
    }) %>%
    mutate(index=1:n()) %>% filter(!is.na(V1))
  sub_dir <- paste0(sub_base_dir,sub,"/",sub,".results/")
  #get the motion information and censor properly
  fdfile <- data.frame(motion=read.table(paste0(sub_dir,"motion_",sub,"_enorm.1D"))$V1) %>%
    mutate(index=1:n(),
           censor_raw=motion>scrubbingThreshold, #censor if over the threshold
           censor_1after=censor_raw | lag(censor_raw,1, default=F), #censor 1 after any censored vols
           censor=censor_1after | (lead(censor_1after,1, default=F) & lag(censor_1after,1, default=F))) #censor any vols between censored vols
  #timecourse length == motion data length error checking
  fdlength <- dim(fdfile)[1]
  nada <- timecourses %>% group_by(parcel) %>%
    summarize(n=n()) %>% group_by(parcel) %>%
    do(thing=if(.$n != fdlength) stop(paste0('fdfile and timecourse ARE NOT SAME LENGTH!!!',
                                             sub, ' ', .$parcel, '\n')))
  #get a summary of motion for filtering later, and just for our info
  motiondata <- summarize(fdfile,
                          Blurps=sum(censor_raw),
                          Numcensored=sum(censor))
  #remove censored volumes
  timecourses_censored <- left_join(timecourses, select(fdfile,index,censor)) %>% filter(!censor)
  #more summary info for filtering subjects later
  motiondata$Framesremaining <- timecourses_censored %>% group_by(parcel) %>% 
    summarize(frames_remaining=n()) %>% distinct(frames_remaining) %>%
    unlist  
  #make the timecourse data nice for correlations
  timecourses_censored_w <- timecourses_censored %>% 
    select(sub, index, parcel, V1) %>% 
    spread(parcel,V1) %>% ungroup %>% select(-index, -sub)
  #correlate!
  CorrelationMatrix<-cor(timecourses_censored_w)
  #just take the bottom triangle
  CorrelationMatrix[upper.tri(CorrelationMatrix, diag=TRUE)] <- NA
  #this gets the names for the rows and columns and assigns each cor value
  #a name that is the combination of the row and column.
  CorrDF <- as.data.frame(CorrelationMatrix) %>% #matrix colnames become df column names
    mutate(var2=rownames(CorrelationMatrix)) %>% #add a column for matrix row names
    gather(var1, cor, -var2) %>% #make wide cor mat long, but keep indexed by matrix row name
    filter(!is.na(cor)) %>% #remove NA (upper tri) rows
    unite(coi, var1, var2) #unite the row and col names, now next to each other, into a single name.
  ## The CorrDF data frame now looks like, for example:
  # key                         cor
  # ---                         -----
  # lh.Parcel_1_lh.Parcel_10    0.338
  ##
  # now we want to add in our summary timecourse info re motion etc, so we just 
  # add columns to the correlation data frame, and turn it into a data table for
  # efficiency later on.
  subjDF <- CorrDF %>% mutate(sub=sub, 
                              Blurps=motiondata$Blurps,
                              Numcensored=motiondata$Numcensored,
                              Framesremaining=motiondata$Framesremaining) %>% as.data.table
  # subjDF <- subjDF %>%
  #   filter(grepl("aseg", coi))
}

# GORDON parcels
system.time(gordon_cois<- mclapply(as.list(sublist$sub),
                                    collectAndCorTimecourses, 
                                    parcels=gordon,
                                    scrubbingThreshold=scrubbingThreshold, 
                                    sub_base_dir=sub_base_dir,
                                    mc.cores=numcores))
print(object.size(gordon_cois), quote = FALSE, units = "Mb")

# bind list of data.tables into one long data.table and filter by frames remaining (< 5 mins)
system.time(gordon_coisDT <- do.call(bind_rows, gordon_cois) %>% 
              filter(Framesremaining >= 385) %>%
              select(-Blurps, -Numcensored, -Framesremaining) %>%  
              as.data.table)
print(object.size(gordon_coisDT), quote = FALSE, units = "Mb")
rm(gordon_cois);gc() #remove list, and garbage collect
save(gordon_coisDT,file = "/Volumes/psych-cog/dsnlab/TAG/TAG_BIDS/derivatives/Nandi_NetworkWorkshop/gordon_coisDT.RDS")

### APARC parcels
system.time(aparc_cois<- mclapply(as.list(sublist$sub),
                                    collectAndCorTimecourses, 
                                    parcels=aparc_parcels,
                                    scrubbingThreshold=scrubbingThreshold, 
                                    sub_base_dir=sub_base_dir,
                                    mc.cores=numcores))
print(object.size(aparc_cois), quote = FALSE, units = "Mb")

# bind list of data.tables into one long data.table and filter by frames remaining (< 5 mins)
system.time(aparc_coisDT <- do.call(bind_rows, aparc_cois) %>% 
              filter(Framesremaining >= 385) %>%
              select(-Blurps, -Numcensored, -Framesremaining) %>%  
              as.data.table)
print(object.size(aparc_coisDT), quote = FALSE, units = "Mb")
rm(aparc_cois);gc() #remove list, and garbage collect
save(aparc_coisDT,file = "/Volumes/psych-cog/dsnlab/TAG/TAG_BIDS/derivatives/Nandi_NetworkWorkshop/aparc_coisDT.RDS")
```
