---
title: "puberty_selfReport"
author: "Nandi"
date: "7 May 2018"
output: html_document
---

###LOAD PACKAGES AND SET DIRECTORIES
```{r, include=FALSE}
packages <- c("nlme", "ggplot2","tidyr", "stringr", "knitr","corrplot","data.table", "readxl", "gridExtra", "dplyr", "psych","kableExtra","lavaan","xlsx")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)

cas_dir <- '/Volumes/psych-cog/dsnlab/TAG/'
age_dir <- paste0(cas_dir,'behavior/Demographics/Age')
quest_dir <- paste0(cas_dir,'behavior/Questionnaires/Wave_1_full')
menarche_dir <- paste0(cas_dir,'behavior/Puberty_Followup')
options(digits=3)
```

###IMPORT TAG OVERVIEW DOC FROM CAS
```{r, include = F}
overview <- read.xlsx(paste0(cas_dir,'behavior/Demographics/Overview_Withdrawn_Completed/TAG_Overview_Doc.xlsx'),1)
overview <- overview[,c("TAG_ID","W1S2_Completed","Withdrawn_W1","Exclusionary_Withdrawl")]

#removing everyone who withdrew at W1 (both self and exclusionary withdrawals)
overview <- overview %>% 
  rename(SID = TAG_ID) %>%
  replace_na(list(Withdrawn_W1 = 0)) %>%
  arrange(Withdrawn_W1) %>% 
  mutate(SID=gsub("[^0-9\\.]", "", SID))
```

###IMPORT AGE
```{r, include=FALSE}
#IMPORT AND CLEAN PDS, PBIP DATA
#import PDS and PBIP datasets, create SID as 3 digit numeric factor (i.e. "001").
Age <- read.xlsx(paste0(age_dir,'/DOB_W1W2_SessionDates.xlsx'), sheetIndex=1)
Age <- Age %>% mutate(SID=str_replace(TAG_ID,"TAG","")) %>% 
  filter(!is.na(SID)) %>%
  select(-TAG_ID) %>%
  mutate(ageS1 = round((W1S1_Date - DOB)/365,3),
         ageS2 = round((W1S2_Date - DOB)/365,3)) %>%
  left_join(.,overview) %>%
  filter(Exclusionary_Withdrawl==0 | is.na(Exclusionary_Withdrawl)) %>%
  filter(!SID=="000")
```

###IMPORT PDS
```{r, include=FALSE}
#IMPORT AND CLEAN PDS
#import PDS, create SID as 3 digit numeric factor (i.e. "001").
#import extra menstruation info from phone calls.

PDS <- read.csv(paste0(quest_dir,'/PDS_Wave1.csv'), header=T)
ExtraMens <- read.xlsx(paste0(menarche_dir,'/Menstruation.xlsx'), sheetIndex=1)

PDS <- PDS %>% mutate(SID=str_replace(tagid,"TAG","")) %>% 
  filter(!grepl("W2",survey_name)) %>% 
  select(SID,contains("PDS"),adrenf2,gonadf2) %>%
  filter(!SID == "034")
ExtraMens <- ExtraMens %>%
  select(tagid,menstruation_by_Wave1SB.before.wave.1) %>%
  rename(Menarche = menstruation_by_Wave1SB.before.wave.1) %>%
  mutate(SID=gsub("[^0-9\\.]", "", tagid)) %>%
  filter(!is.na(SID)) %>%
  mutate(Menarche = ifelse(Menarche=="yes",1,0))
Menarche = as.list(ExtraMens %>% filter(Menarche==1) %>% select(SID) %>% arrange(SID))
NoMenarche = as.list(ExtraMens %>% filter(Menarche==0) %>% select(SID) %>% arrange(SID))
  
PDS <- PDS %>%
  mutate(PDS_F6 = ifelse(!is.na(PDS_F6),PDS_F6,
                      ifelse(is.na(PDS_F6) & SID %in% Menarche$SID, 1,
                             ifelse(is.na(PDS_F6) & SID %in% NoMenarche$SID, 0, NA)))) %>%
  mutate(pdss2 = trunc(pdss))
```

###IMPORT PBIP
```{r, include=FALSE}
#IMPORT AND CLEAN PBIP 
#import PBIP, create SID as 3 digit numeric factor (i.e. "001").
PBIP <- read.csv(paste0(quest_dir,'/PBIP_Wave1.csv'), header=T)

PBIP <- PBIP %>% mutate(SID=str_replace(tagid,"TAG",""),
                        PBIP_stage=stage) %>%
  filter(!grepl("W2",survey_name)) %>% 
  select(SID,contains("PBIP")) %>%
  filter(!SID == "034")
```

###SCORE PARENT PDS
```{r, include=FALSE}
PDS_parent1 <- read.csv("~/Desktop/TAG_ParentPDS1.csv",header=T)
PDS_parent2 <- read.csv("~/Desktop/TAG_ParentPDS2.csv",header=T)

PDS_parent1 <- PDS_parent1 %>% select("SID","PDS_F1","PDS_F2","PDS_F3","PDS_F4","PDS_F5","PDS_F6","PDS_F7","PDS_F8")
PDS_parent2 <- PDS_parent2 %>% select("SID","PDS_F1","PDS_F2","PDS_F3","PDS_F4","PDS_F5","PDS_F6","PDS_F7","PDS_F8")

PDS_parent <- PDS_parent1 %>% full_join(., PDS_parent2) %>%
  mutate(SID=as.numeric(SID)) %>% filter(!is.na(SID))

PDS_parent$SID <- sprintf("%03d", PDS_parent$SID)

PDS_parent<-PDS_parent %>% 
  mutate(peta=PDS_F1,
         petb=PDS_F2,
         petc=PDS_F3,
         petd=PDS_F4,
         fpete=PDS_F6,
         petaf=ifelse(PDS_F1==1,1,
                      ifelse(PDS_F1==2,2,
                             ifelse(PDS_F1==3,3,
                                    ifelse(PDS_F1==4,5,
                                           NA)))),
         petbf=ifelse(PDS_F2==1,1,
                      ifelse(PDS_F2==2,2,
                             ifelse(PDS_F2==3,4,
                                    ifelse(PDS_F2==4,5,
                                           NA)))),
         petcf=ifelse(PDS_F3==1,1,
                      ifelse(PDS_F3==2,2,
                             ifelse(PDS_F3==3,4,
                                    ifelse(PDS_F3==4,5,
                                           NA)))),
         petdf=ifelse(PDS_F4==1,1,
                      ifelse(PDS_F4==2,3,
                             ifelse(PDS_F4==3,4,
                                    ifelse(PDS_F4==4,5,
                                           NA)))),         
         petef=ifelse(PDS_F6==0,1,
                      ifelse(PDS_F6==1,5,
                             NA))) %>%
  mutate(adrenf=rowMeans(cbind(petbf,petcf),na.rm=F)) %>%
  mutate(adrenf2=ifelse(adrenf==1,1,
                        ifelse(petb==1 & adrenf==1.5,1,
                               ifelse(petb==2 & adrenf==1.5,2,
                                      ifelse(adrenf==2,2,
                                             ifelse(adrenf==2.5,3,
                                                    ifelse(adrenf==3,3,
                                                           ifelse(adrenf==3.5,4,
                                                                  ifelse(adrenf==4,4,
                                                                         ifelse(adrenf==4.5,5,
                                                                                ifelse(adrenf==5,5,
                                                                                       NA))))))))))) %>%
  mutate(gonadf=rowMeans(cbind(petaf,petdf),na.rm=F)) %>%
  mutate(gonadf2=ifelse(gonadf==1 & petef==1,1,
                        ifelse(gonadf==1.5 & petef==1,1,
                               ifelse(gonadf==2 & petef==1,2,
                                      ifelse(gonadf==2.5 & petef==1,2,
                                             ifelse(gonadf==3 & petef==1,3,
                                                    ifelse(gonadf==3.5 & petef==1,3,
                                                           ifelse(gonadf==4 & petef==1,3,
                                                                  ifelse(gonadf==4.5 & petef==1,4,
                                                                         ifelse(gonadf==5 & petef==1,4,
                                                                                ifelse(gonadf==1 & petef==5,2,
                                                                                       ifelse(gonadf==1.5 & petef==5,3,
                                                                                              ifelse(gonadf==2 & petef==5,4,
                                                                                                     ifelse(gonadf==2.5 & petef==5,4,
                                                                                                            ifelse(gonadf==3 & petef==5,4,
                                                                                                                   ifelse(gonadf==3.5 & petef==5,5,
                                                                                                                          ifelse(gonadf==4 & petef==5,5,
                                                                                                                                 ifelse(gonadf==4.5 & petef==5,5,
                                                                                                                                        ifelse(gonadf==5 & petef==5,5,
                                                                                                                                               NA))))))))))))))))))) %>%
  mutate(pdss=rowMeans(cbind(adrenf2,gonadf2),na.rm=F)) 

PDS_parent <- PDS_parent %>% 
  rename(PDS_F1_p = PDS_F1,
         PDS_F2_p = PDS_F2,
         PDS_F3_p = PDS_F3,
         PDS_F4_p = PDS_F4,
         PDS_F6_p = PDS_F6,
         adrenf2_p = adrenf2,
         gonadf2_p = gonadf2,
         pdss_p = pdss) %>%
  filter(!((PDS_F1_p=="") & (PDS_F2_p=="") & (PDS_F3_p=="") & (PDS_F4_p=="") & (PDS_F6_p==""))) %>%
  mutate(PDS_F1_p = as.numeric(as.character(PDS_F1_p)),
         PDS_F2_p = as.numeric(as.character(PDS_F2_p)),
         PDS_F3_p = as.numeric(as.character(PDS_F3_p)),
         PDS_F4_p = as.numeric(as.character(PDS_F4_p)),
         PDS_F6_p = as.numeric(as.character(PDS_F6_p))) %>%
  select(SID, contains("_p"))

```

###COMBINE PDS & PBIP & PDS_p
```{r, include=FALSE}
Qdf <- PDS %>% full_join(.,PBIP) %>% full_join(.,PDS_parent)

Qdf_items <- Qdf %>% select(-pdss,-pdss2,-gonadf2,-adrenf2,-PDS_F5,-PDS_F7,-PDS_F8,-PDS_F9,-PBIP_stage,-PBIP_1B,-PBIP_2B, -adrenf2_p, -gonadf2_p, -pdss_p)
```

###DISTRIBUTIONS
```{r, echo=FALSE, message=FALSE, warning=FALSE, results="asis", fig.height=7, fig.width=7}
barplot_age <- ggplot(subset(Age, !is.na(ageS1)), aes(round(as.numeric(ageS1),2))) +
    geom_histogram(binwidth = 0.1, colour="white", fill="grey28",
                   breaks=seq(9.8, 13.5, by = 0.25))+
    xlim(9.5,13.5) +
    xlab("Age") +
    scale_y_continuous(limits = c(0, 35), breaks = seq(0,35,by=5))+
    theme_bw() +
    theme_minimal(base_size = 12, base_family = "Arial") +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position="none")

barplot_PDS <- ggplot(subset(Qdf, !is.na(pdss2)), aes((pdss2))) +
    geom_bar() + 
    xlim(0.5,5.5) +
    xlab("PDS")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0,60,by=10))+
    theme_bw() +
    theme_minimal(base_size = 12, base_family = "Arial") +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position="none")

barplot_PDSadren <- ggplot(subset(Qdf, !is.na(adrenf2)), aes((adrenf2))) +
    geom_bar() + 
    xlim(0.5,5.5) +
    xlab("Adrenal")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0,60,by=10))+
    theme_bw() +
    theme_minimal(base_size = 12, base_family = "Arial") +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position="none")

barplot_PDSgonad <- ggplot(subset(Qdf, !is.na(gonadf2)), aes((gonadf2))) +
    geom_bar() + 
    xlim(0.5,5.5) +
    xlab("Gonadal")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0,60,by=10))+
    theme_bw() +
    theme_minimal(base_size = 12, base_family = "Arial") +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position="none")

barplot_PBIP <- ggplot(subset(Qdf, !is.na(PBIP_stage)), aes(trunc(PBIP_stage))) +
    geom_bar() + 
    xlim(0.5,5.5) +
    xlab("PBIP")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0,60,by=5))+
    theme_bw() +
    theme_minimal(base_size = 12, base_family = "Arial") +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position="none")

barplot_PDS_p <- ggplot(subset(Qdf, !is.na(pdss_p)), aes(trunc(pdss_p))) +
    geom_bar() + 
    xlim(0.5,5.5) +
    xlab("PDS p")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0,60,by=10))+
    theme_bw() +
    theme_minimal(base_size = 12, base_family = "Arial") +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position="none")

barplot_PDSadren_p <- ggplot(subset(Qdf, !is.na(adrenf2_p)), aes((adrenf2_p))) +
    geom_bar() + 
    xlim(0.5,5.5) +
    xlab("Adrenal P")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0,60,by=10))+
    theme_bw() +
    theme_minimal(base_size = 12, base_family = "Arial") +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position="none")

barplot_PDSgonad_p <- ggplot(subset(Qdf, !is.na(gonadf2_p)), aes((gonadf2_p))) +
    geom_bar() + 
    xlim(0.5,5.5) +
    xlab("Gonadal P")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0,60,by=10))+
    theme_bw() +
    theme_minimal(base_size = 12, base_family = "Arial") +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position="none")


scale_dist <- Qdf %>%
  select(pdss,adrenf2,gonadf2,PBIP_stage,pdss_p,adrenf2_p,gonadf2_p) %>%
  gather() %>% 
  ggplot(aes(trunc(value))) +
    facet_wrap(~ key, scales = "free") +
    geom_bar() + 
    xlim(0.5,5.5) +
    scale_y_continuous(limits = c(0, 70), breaks = seq(0,80,by=20))+
    theme_bw() +
    theme_minimal(base_size = 12, base_family = "Arial") +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position="none")


item_dist <- Qdf_items %>%
  select(-SID) %>%
  mutate(PDS_F6 = ifelse(PDS_F6==1,2,
                         ifelse(PDS_F6==0,1,
                                NA)),
         PDS_F6_p = ifelse(PDS_F6_p==1,2,
                         ifelse(PDS_F6_p==0,1,
                                NA))) %>%
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_bar() + 
    xlim(0.5,5.5) +
    scale_y_continuous(limits = c(0, 120), breaks = seq(0,120,by=20))+
    theme_bw() +
    theme_minimal(base_size = 12, base_family = "Arial") +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position="none")

barplot_age
scale_dist
item_dist
```

###CORRELATION MATRIX
```{r, echo=FALSE}
corr_df <- Qdf[-1] %>% select(-PDS_F5,-PDS_F7,-PDS_F8,-PDS_F9,-pdss2,-PBIP_1B,-PBIP_2B)
corr_plot <- cor(corr_df,use="pairwise.complete.obs")
res1 <- corr.test(corr_df, adjust = "none")
corr_heatmap_overall <- corrplot(corr_plot, p.mat = res1$p, method = "color", type = "upper",
                                 sig.level = c(0.001,0.01,0.05), pch.cex = .9,
                                 insig = "label_sig", pch.col = "white")

kable(corr_plot, "html", align='c', caption = "Correlation Coefficients") %>%
  kable_styling(full_width = F, position = "left", font_size = 12)

count <- count.pairwise(corr_df)
kable(count, "html", align='c', caption = "Sample size of pairwise comparisons") %>%
  kable_styling(full_width = F, position = "left", font_size = 12)
```
