---
title: "score_SCSC"
author: "MEAB"
date: "July 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
#insert prep functions here
#workdir="Y:/dsnlab/TAG/behavior/"
```

Scoring SCS-C # Do not submit to RDOC
```{r}
SCSC_Roles <- left_join(filter(cleaned_survey_data, grepl("^SCS_C_Roles",item)) %>%
                          mutate(value=as.character(value)) %>%
                          filter(!value=="") %>%
                          distinct(tagid,item,value,survey_name,.keep_all = FALSE) %>% 
                          subset(!tagid=="TAG200" | !survey_name=="W2S1 - V1") %>% 
                          spread(item,value),
                        redcap_cleaned %>%
                          filter(!is.na(dob),!is.na(sa_date)) %>%
                          select(tagid, sa_date, sb_date, dob),by="tagid")
SCSC_Adj <- left_join(filter(cleaned_survey_data, grepl("^SCS_C",item)) %>%
                        mutate(value=as.numeric(value)) %>% 
                        filter(!value=="") %>%
                        distinct(tagid,item,value,survey_name,.keep_all = FALSE) %>% 
                        subset(!tagid=="TAG200" | !survey_name=="W2S1 - V1") %>%
                        spread(item,value),
                      redcap_cleaned %>%
                        filter(!is.na(dob),!is.na(sa_date)) %>%
                        select(tagid, sa_date, sb_date, dob),by="tagid")
SCSC <- left_join(SCSC_Roles, SCSC_Adj)
if (length(SCSC$tagid) == length(unique(SCSC$tagid))){
  print("No duplicate TAGIDs in data")
} else {
  print("DUPLICATE TAGIDs in data")
}
SCSC_all<-left_join(SCSC,survey_date, by = c("tagid","survey_name")) %>% 
  distinct(tagid,survey_name,.keep_all = TRUE) %>%
  mutate(qualtrics_date=value) %>%
  select(-value)%>%
  mutate(survey_date=ifelse(survey_name=="TAG - Sess 2 - V1",sb_date,
                            ifelse(survey_name=="Sensitive Q's for 042",sb_date,as.character(qualtrics_date)
                            ))) %>%
  select(-qualtrics_date,-sb_date,-sa_date,-dob) %>%
  mutate(SCS_C_Roles_1_TEXT=ifelse(is.na(SCS_C_Roles_1_TEXT),0,1),
         SCS_C_Roles_2_TEXT=ifelse(is.na(SCS_C_Roles_2_TEXT),0,1),
         SCS_C_Roles_3_TEXT=ifelse(is.na(SCS_C_Roles_3_TEXT),0,1),
         SCS_C_Roles_4_TEXT=ifelse(is.na(SCS_C_Roles_4_TEXT),0,1),
         SCS_C_Roles_5_TEXT=ifelse(is.na(SCS_C_Roles_5_TEXT),0,1),
         SCS_C_Roles_6_TEXT=ifelse(is.na(SCS_C_Roles_6_TEXT),0,1),
         SCS_C_Roles_7_TEXT=ifelse(is.na(SCS_C_Roles_7_TEXT),0,1),
         SCS_C_Roles_8_TEXT=ifelse(is.na(SCS_C_Roles_8_TEXT),0,1),
         SCS_C_Roles_9_TEXT=ifelse(is.na(SCS_C_Roles_9_TEXT),0,1),
         SCS_C_Roles_10_TEXT=ifelse(is.na(SCS_C_Roles_10_TEXT),0,1),
         SCS_C_NASPECTS=rowSums(cbind(SCS_C_Roles_1_TEXT, SCS_C_Roles_2_TEXT,
                                      SCS_C_Roles_3_TEXT, SCS_C_Roles_4_TEXT,
                                      SCS_C_Roles_5_TEXT, SCS_C_Roles_6_TEXT,
                                      SCS_C_Roles_7_TEXT, SCS_C_Roles_8_TEXT,
                                      SCS_C_Roles_9_TEXT, SCS_C_Roles_10_TEXT), na.rm = F)) %>% 
  mutate(SCS_C_Group_Happy=as.character(paste0(SCS_C_1_1, SCS_C_2_1, SCS_C_3_1, SCS_C_4_1, SCS_C_5_1, SCS_C_6_1, SCS_C_7_1, SCS_C_8_1, SCS_C_9_1, SCS_C_10_1)),
         SCS_C_Group_Smart=as.character(paste0(SCS_C_1_2, SCS_C_2_2, SCS_C_3_2, SCS_C_4_2, SCS_C_5_2, SCS_C_6_2, SCS_C_7_2, SCS_C_8_2, SCS_C_9_2, SCS_C_10_2)),
         SCS_C_Group_Brave=as.character(paste0(SCS_C_1_3, SCS_C_2_3, SCS_C_3_3, SCS_C_4_3, SCS_C_5_3, SCS_C_6_3, SCS_C_7_3, SCS_C_8_3, SCS_C_9_3, SCS_C_10_3)),
         SCS_C_Group_Helpful=as.character(paste0(SCS_C_1_4, SCS_C_2_4, SCS_C_3_4, SCS_C_4_4, SCS_C_5_4, SCS_C_6_4, SCS_C_7_4, SCS_C_8_4, SCS_C_9_4, SCS_C_10_4)),
         SCS_C_Group_Nice=as.character(paste0(SCS_C_1_5, SCS_C_2_5, SCS_C_3_5, SCS_C_4_5, SCS_C_5_5, SCS_C_6_5, SCS_C_7_5, SCS_C_8_5, SCS_C_9_5, SCS_C_10_5)),
         SCS_C_Group_Angry=as.character(paste0(SCS_C_1_6, SCS_C_2_6, SCS_C_3_6, SCS_C_4_6, SCS_C_5_6, SCS_C_6_6, SCS_C_7_6, SCS_C_8_6, SCS_C_9_6, SCS_C_10_6)),
         SCS_C_Group_Lonely=as.character(paste0(SCS_C_1_7, SCS_C_2_7, SCS_C_3_7, SCS_C_4_7, SCS_C_5_7, SCS_C_6_7, SCS_C_7_7, SCS_C_8_7, SCS_C_9_7, SCS_C_10_7)),
         SCS_C_Group_Lazy=as.character(paste0(SCS_C_1_8, SCS_C_2_8, SCS_C_3_8, SCS_C_4_8, SCS_C_5_8, SCS_C_6_8, SCS_C_7_8, SCS_C_8_8, SCS_C_9_8, SCS_C_10_8)),
         SCS_C_Group_Bad=as.character(paste0(SCS_C_1_9, SCS_C_2_9, SCS_C_3_9, SCS_C_4_9, SCS_C_5_9,
SCS_C_6_9, SCS_C_7_9, SCS_C_8_9, SCS_C_9_9, SCS_C_10_9)),
         SCS_C_Group_Scared=as.character(paste0(SCS_C_1_10, SCS_C_2_10, SCS_C_3_10, SCS_C_4_10, SCS_C_5_10, SCS_C_6_10, SCS_C_7_10, SCS_C_8_10, SCS_C_9_10, SCS_C_10_10)),
         SCS_C_Group_Responsible=as.character(paste0(SCS_C_1_11, SCS_C_2_11, SCS_C_3_11, SCS_C_4_11, SCS_C_5_11, SCS_C_6_11, SCS_C_7_11, SCS_C_8_11, SCS_C_9_11, SCS_C_10_11)),
         SCS_C_Group_Confident=as.character(paste0(SCS_C_1_12, SCS_C_2_12, SCS_C_3_12, SCS_C_4_12, SCS_C_5_12,  SCS_C_6_12, SCS_C_7_12, SCS_C_8_12, SCS_C_9_12, SCS_C_10_12)),
         SCS_C_Group_Kind=as.character(paste0(SCS_C_1_13, SCS_C_2_13, SCS_C_3_13, SCS_C_4_13, SCS_C_5_13, SCS_C_6_13, SCS_C_7_13, SCS_C_8_13, SCS_C_9_13, SCS_C_10_13)),
         SCS_C_Group_Calm=as.character(paste0(SCS_C_1_14, SCS_C_2_14, SCS_C_3_14, SCS_C_4_14, SCS_C_5_14, SCS_C_6_14, SCS_C_7_14, SCS_C_8_14, SCS_C_9_14, SCS_C_10_14)),
         SCS_C_Group_Funny=as.character(paste0(SCS_C_1_15, SCS_C_2_15, SCS_C_3_15, SCS_C_4_15, SCS_C_5_15, SCS_C_6_15, SCS_C_7_15, SCS_C_8_15, SCS_C_9_15, SCS_C_10_15)),
         SCS_C_Group_Ugly=as.character(paste0(SCS_C_1_16, SCS_C_2_16, SCS_C_3_16, SCS_C_4_16, SCS_C_5_16, SCS_C_6_16, SCS_C_7_16, SCS_C_8_16, SCS_C_9_16, SCS_C_10_16)),
         SCS_C_Group_Sad=as.character(paste0(SCS_C_1_17, SCS_C_2_17, SCS_C_3_17, SCS_C_4_17, SCS_C_5_17, SCS_C_6_17, SCS_C_7_17, SCS_C_8_17, SCS_C_9_17, SCS_C_10_17)),
         SCS_C_Group_Shy=as.character(paste0(SCS_C_1_18, SCS_C_2_18, SCS_C_3_18, SCS_C_4_18, SCS_C_5_18, SCS_C_6_18, SCS_C_7_18, SCS_C_8_18, SCS_C_9_18, SCS_C_10_18)),
         SCS_C_Group_Confused=as.character(paste0(SCS_C_1_19, SCS_C_2_19, SCS_C_3_19, SCS_C_4_19, SCS_C_5_19, SCS_C_6_19, SCS_C_7_19, SCS_C_8_19, SCS_C_9_19, SCS_C_10_19)),
         SCS_C_Group_Careless=as.character(paste0(SCS_C_1_20, SCS_C_2_20, SCS_C_3_20, SCS_C_4_20, SCS_C_5_20, SCS_C_6_20, SCS_C_7_20, SCS_C_8_20, SCS_C_9_20, SCS_C_10_20)))
SCSC_clean <- SCSC_all %>% select(tagid, survey_name, SCS_C_Group_Happy, SCS_C_Group_Smart,             SCS_C_Group_Brave, SCS_C_Group_Helpful, SCS_C_Group_Nice, SCS_C_Group_Angry, SCS_C_Group_Lonely,     SCS_C_Group_Lazy, SCS_C_Group_Bad, SCS_C_Group_Scared, SCS_C_Group_Responsible,                     SCS_C_Group_Confident, SCS_C_Group_Kind, SCS_C_Group_Calm, SCS_C_Group_Funny, SCS_C_Group_Ugly, 
    SCS_C_Group_Sad, SCS_C_Group_Shy, SCS_C_Group_Confused, SCS_C_Group_Careless)
SCSC_Groups <- SCSC_clean %>% select(-tagid, -survey_name)
SCSC_Groups_pos <- SCSC_clean %>% select(SCS_C_Group_Happy, SCS_C_Group_Smart, SCS_C_Group_Brave,                                      SCS_C_Group_Helpful, SCS_C_Group_Nice, SCS_C_Group_Responsible,                                     SCS_C_Group_Confident, SCS_C_Group_Kind, SCS_C_Group_Calm,  
                                  SCS_C_Group_Funny)
SCSC_Groups_neg <- SCSC_clean %>% select(SCS_C_Group_Angry, SCS_C_Group_Lonely, SCS_C_Group_Lazy, 
                                         SCS_C_Group_Bad, SCS_C_Group_Scared, SCS_C_Group_Ugly, 
                                         SCS_C_Group_Sad, SCS_C_Group_Shy, SCS_C_Group_Confused,                                             SCS_C_Group_Careless)
#SCSC_Groups$patterncount <- apply(SCSC_Groups, 1, function(x)length(unique(x)))
options(scipen = 999)
SCSC_freq <- apply(SCSC_Groups,MARGIN=1,table)
SCSC_freq_pos <- apply(SCSC_Groups_pos,MARGIN=1,table)
SCSC_freq_neg <- apply(SCSC_Groups_neg,MARGIN=1,table)
#For the formula, see Abela & Veronneau-McArdle 2002
for (p in 1:length(SCSC_freq)) {
  xi_all =  unlist(SCSC_freq[p], use.names = F)
  logging <- function(x) {x*log2(x)}
  xi_log =  sapply(xi_all, FUN=logging)
  patternform = sum(xi_log)
  SCSC_clean[p,"Total_selfcomplexity"] <- log2(20) - patternform / 20 }

for (p in 1:length(SCSC_freq_pos)) {
  xi_all =  unlist(SCSC_freq_pos[p], use.names = F)
  logging <- function(x) {x*log2(x)}
  xi_log =  sapply(xi_all, FUN=logging)
  patternform = sum(xi_log)
  SCSC_clean[p,"Pos_selfcomplexity"] <- round(log2(10) - patternform / 10, digits=4) }

for (p in 1:length(SCSC_freq_neg)) {
  xi_all =  unlist(SCSC_freq_neg[p], use.names = F)
  logging <- function(x) {x*log2(x)}
  xi_log =  sapply(xi_all, FUN=logging)
  patternform = sum(xi_log)
  SCSC_clean[p,"Neg_selfcomplexity"] <- round(log2(10) - patternform / 10, digits=4) }

## Save it
SCSC_Wave1_outdf <- SCSC_clean %>% filter(!grepl("W2|W3",survey_name)) 
write.csv(SCSC_Wave1_outdf, file = paste0(workdir,"Questionnaires/Wave1/SCSC_Wave1.csv"))
SCSC_Wave2_outdf <- SCSC_clean %>% filter(grepl("W2",survey_name)) 
write.csv(SCSC_Wave2_outdf, file = paste0(workdir,"Questionnaires/Wave2/SCSC_Wave2.csv"))
SCSC_Wave3_outdf <- SCSC_clean %>% filter(grepl("W3",survey_name)) 
write.csv(SCSC_Wave3_outdf, file = paste0(workdir,"Questionnaires/Wave3/SCSC_Wave3.csv"))

```